### ISSUE TITLE
Добавить определение старых новостей среди импортированых

### ISSUE THREAD

**Issue by alrusdi** [alrusdi/python-news-digest#46]
Воспользоваться, например, возможностью поиска в гугле по URL и оператору daterange.
Например: "site:**проверяемый url** daterange:**julian_date_start**-**julian date end**"
Где julian date это Юлианская дата, которую можно вычислить из Грегорианской так code-highlights.blogspot.ru/2013/01/julian-date-in-python.html или jdcal заюзать

**Comment by PixxxeL** [comment]
Надо тестить

**Comment by alrusdi** [comment]
Спасибо!
